services:
  python:
    build: 
      context: python/
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_network
    restart: always
  
  golang:
    build:
      context: golang/
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_network
    restart: always

  rabbitmq:
    attach: false
    image: "rabbitmq:latest"
    networks:
      - rabbitmq_network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s

networks:
  rabbitmq_network:
    driver: bridge
