services:
  python:
    build: 
      context: python/
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_network

  rabbitmq:
    image: "rabbitmq:latest"
    networks:
      - rabbitmq_network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: always

networks:
  rabbitmq_network:
    driver: bridge